import * as fflate from "fflate";
import fs from "node:fs/promises";
import path from "node:path";

/**
 * Encapsulates the multi-platform image archive ZIP generated by PWABuilder.
 */
export class ImageArchive {
  private readonly buffer: Buffer;
  private readonly unzipped: Record<string, Uint8Array>;

  public constructor(zipData: ArrayBuffer | Buffer | Uint8Array) {
    this.buffer = Buffer.isBuffer(zipData) ? zipData : Buffer.from(new Uint8Array(zipData));
    this.unzipped = fflate.unzipSync(new Uint8Array(this.buffer));
  }

  public toBuffer(): Buffer {
    return this.buffer;
  }

  public getFileNames(): readonly string[] {
    return Object.keys(this.unzipped);
  }

  public async extractTo(targetDirectory: string): Promise<readonly string[]> {
    const writtenPaths: string[] = [];
    for (const [relativePath, data] of Object.entries(this.unzipped)) {
      const fullPath = path.join(targetDirectory, relativePath);
      await this.ensureParentDirectory(fullPath);
      await fs.writeFile(fullPath, Buffer.from(data));
      writtenPaths.push(fullPath);
    }
    return Object.freeze(writtenPaths);
  }

  private async ensureParentDirectory(filePath: string): Promise<void> {
    const dir = path.dirname(filePath);
    await fs.mkdir(dir, { recursive: true });
  }
}
